### ISSUE TITLE
udisks2 installation error resulting in crash at launch

### ISSUE THREAD

**Issue by crawfordlong** [damonlynch/rapid-photo-downloader#104]
This doesn't seem to be as much an error with rapid-photo-downloader as it is with a dependency, specifically udisks2. When installing udisks2 **in a distrobox container** via dnf, the installation log shows an error installing udisks2. There is also an error installing udisks2 standalone first **in the distrobox container** via dnf. 

Layering udisks2 on the base image doesn't seem to make any difference (there are a couple of things I might be able to try with that, however). 

rapid-photo-downloader will then either fail to launch or launch with an error, crashing out almost immediately.

What seems to be happening, and I haven't had a chance to really dig into this, is that the udisks2 dependency doesn't like living in the container and cannot access the resources it is expecting. In a way this is an edge case because it's occurring on a semi-experimental branch of one distro (just to make it more ridiculous, I'm using the sway window manager), but I'm wondering if there's some sort of workaround for this specific dependency.

**Comment by damonlynch** [comment]
udisks2 is an absolutely essential component of Rapid Photo Downloader, used to detect the presence / removal of hardware devices. I would be hugely surprised if udisks2 would run within any kind of container &mdash; unless the hardware is virtualised, or the device is somehow passed through to the container (very hard to see how that makes any sense).

As such, there is no work around that I can think of.
