### ISSUE TITLE
Unable to compare ExifTool version number on Arch

### ISSUE THREAD

**Issue by sebw** [damonlynch/rapid-photo-downloader#108]
Concerns Arch Linux.

When installing from either extra or AUR I was getting:

`ERROR:root:Unable to compare ExifTool version number: unknown`

Upon further investigation in code I realize you call `exiftool` while for some reason the binary on Arch is `exif`.

My workaround was to symlink `sudo ln -s exif exiftool`

**Comment by damonlynch** [comment]
We can add it to the list of things where Linux distros are doing something different from one another! Could you please write a patch that detects when an Arch like approach is taken, and calls the right executable?

**Comment by sebw** [comment]
After investigating this further, it turns out the exif binary is owned by the exif package. Adding /usr/bin/vendor_perl to the PATH solves this (arch) issue. Thanks! Closing for now.
