### ISSUE TITLE
Video download fails at 62% (Canon 5D Mark IV)

### ISSUE THREAD

**Issue by theoo** [damonlynch/rapid-photo-downloader#120]
Photo download works as expected.

Video download always get stalled at 62%, no matter which video and if there is only one or many selected for download.
Created folders on the computer are empty will be removed once the Rapid-Photo-Downloader is closed. 

Downloading videos with CF card mounted (FS) from the camera _or_ with an external adapter will work. Download with other MTP tools like shotwell worked just fine.

Version and platform are available in the attached log file.
Note that gihub prevent uploading a compressed archive (tar.gz).

[rapid-photo-downloader.0.log](https://github.com/damonlynch/rapid-photo-downloader/files/13771707/rapid-photo-downloader.0.log)
[Rapid Photo Downloader.conf.txt](https://github.com/damonlynch/rapid-photo-downloader/files/13771713/Rapid.Photo.Downloader.conf.txt)

Thanks for this cool software.

**Comment by theoo** [comment]
To complete the report, video download:
- taken with Canon 5D Mark II using an external CF Adapter: hangs at 95%
- Canon EOS R, directly from the camera: hangs at 62%

Can it be that I'm missing a lib under archlinux?

**Comment by damonlynch** [comment]
Try again with the compressed tar. I was able to upload one myself just now.

**Comment by damonlynch** [comment]
Closing due to lack of response.
