### ISSUE TITLE
Application crashes on start on openSUSE Tumbleweed

### ISSUE THREAD

**Issue by bozhink** [damonlynch/rapid-photo-downloader#122]
Application crashes on start on openSUSE Tumbleweed
[rpd-bug-report-20240206.tar.gz](https://github.com/damonlynch/rapid-photo-downloader/files/14177107/rpd-bug-report-20240206.tar.gz)

The problem is that the system file "/etc/os-release" contains lines which cannot be split into array of 2 items [k, v].

**Comment by damonlynch** [comment]
I have released 0.9.36 which contains the fix for this problem

**Comment by 131706dulce** [comment]
> Application crashes on start on openSUSE Tumbleweed [rpd-bug-report-20240206.tar.gz](https://github.com/damonlynch/rapid-photo-downloader/files/14177107/rpd-bug-report-20240206.tar.gz)
> 
> The problem is that the system file "/etc/os-release" contains lines which cannot be split into array of 2 items [k, v].
sudo apt install rapid-photo-downloader

**Comment by 131706dulce** [comment]
sudo apt install rapid-photo-downloader
