### ISSUE TITLE
Import Stuck at 62%

### ISSUE THREAD

**Issue by misaligar** [damonlynch/rapid-photo-downloader#125]
I can't import photos/videos from the SD card to my Arch Linux PC. `rpd-tmp` folders are created but they have not moved to the actual destination. RPD shows 62% at the bottom right. And a message at the bottom left says:

`Downloading from 3339-8D9C - A few seconds left (0.0 MB/sec`.

I have waited several minutes. Nothing changed.

I can confirm that the `rpd-tmp` folders contain the photos/videos from the SD card.

I downloaded RPD via `pacman` from the `extra` library. And the RPD version is `0.9.35-1`.

I started `RPD` from the Terminal and got the following error message during the import:

![image](https://github.com/damonlynch/rapid-photo-downloader/assets/42714627/3eaafdd5-6715-40b2-a17c-d0c15ad9922f)

**Comment by damonlynch** [comment]
Thanks for your bug report. This was fixed in 0.9.36. Because of that, I'm closing the report.

**Comment by misaligar** [comment]
@damonlynch Thanks, I understand. Arch Linux package is out of date. I guess I will have to wait for the maintainer to update it.
