### ISSUE TITLE
How to compile the source

### ISSUE THREAD

**Issue by misaligar** [damonlynch/rapid-photo-downloader#126]
I searched the documentation but could not find it. How can I compile the source myself? My best guess is that I need to run `setup.py` file but not sure what parameters to use. Thank you.

**Comment by misaligar** [comment]
I don't know if I did the right thing, but I ran

````
python setup.py build
python setup.py install
```
and it seems to be working fine when I run from the command line.

I just need to create a desktop shortcut manually.

**Comment by damonlynch** [comment]
I'm glad you figured it out, but I hope you did not use `sudo` at the install step!

**Comment by damonlynch** [comment]
In future for python programs, you may wish to consult this: https://packaging.python.org/en/latest/discussions/setup-py-deprecated/
