### ISSUE TITLE
Copying videos gets stuck at 95%

### ISSUE THREAD

**Issue by thehamstermuffin** [damonlynch/rapid-photo-downloader#135]
Using version 0.9.35

Just trying to copy any video it gets stuck.
If copying several files it gets stuck when it gets to the first video on the queue

https://github.com/damonlynch/rapid-photo-downloader/assets/16860332/ad79e4ac-4366-430b-bdbe-bdaf591fed9b

**Comment by damonlynch** [comment]
Thanks, this was fixed in 0.9.36
