### ISSUE TITLE
Permission issue - cannot set a download location

### ISSUE THREAD

**Issue by brownphotographic** [damonlynch/rapid-photo-downloader#231]
Hi, 

I recently reinstalled this utility onto Linux Mint 22. I have some permissions issues I think that are preventing me from setting a download location. When I try to set it (any folder) I get a message: 

```
Invalid photo download destination

The download directory is not writable. Ensure permissions are correctly set. If the destination is on the network, ensure the network share is correctly configured.
```

Thank you for any pointers.

![Screenshot from 2024-08-16 08-01-46](https://github.com/user-attachments/assets/375869fe-ac08-48dd-a12a-640a896767b8)

**Comment by damonlynch** [comment]
What folder are you trying to choose? How are you trying to choose it? Have you ensured that the folder is not read-only?

**Comment by brownphotographic** [comment]
I'm trying to access any folder off home, but when I click on home/myhomedirectoryname then the program hangs and I get that message.

**Comment by brownphotographic** [comment]
as far as I can tell that folder doesn't have permission problems (not read only)

**Comment by damonlynch** [comment]
The error message indicates the folder you were choosing is not
writable for your user. Please doublecheck this using a commandline tool, or a file manager.

**Comment by brownphotographic** [comment]
OK I will try to check..

Right now though it seems Rapid Photo Downloader won't even boot and just sticks on the launch screen (even after system reboot)? Maybe I have some bigger problems in play with my system and perhaps the latest Linux Mint 22 is to blame here.

**Comment by damonlynch** [comment]
I will close this issue for now. If the home directory you were using is in fact not read only then feel free to reopen it.
