### ISSUE TITLE
Option to disable thumbnail generation / hanging on splashscreen on first run

### ISSUE THREAD

**Issue by eMPee584** [damonlynch/rapid-photo-downloader#232]
Can this be skipped somehow:

```
DEBUG    Thumbnail-Extractor-4 worker started
DEBUG    Thumbnail-Extractor-0 worker started
DEBUG    Thumbnail-Extractor-3 worker started
DEBUG    Thumbnail-Extractor-5 worker started
DEBUG    Thumbnail-Extractor-2 worker started
DEBUG    Thumbnail-Extractor-1 worker started
```
I have a zillion files all over and just wanted to quickly backup a mate's iphone images 🥲

**Comment by damonlynch** [comment]
Did you read the documentation? That has answers to your question. https://damonlynch.net/rapid/documentation/#thumbnailpreferences

If the program is hanging, submit a separate issue, if possible using the built-in report a problem feature in the hamburger menu .

**Comment by eMPee584** [comment]
There is no hamburger menu on the hanging splash screen. I can not access the preferences because this is the first run. The program also is eating all CPU and RAM while doing it.

**Comment by damonlynch** [comment]
And by the way, if you are downloading from an iPhone, Rapid Photo Downloader downloads the entire file in order to be able to generate a thumbnail, and as long as you don't exit the program, caches the end tire file making the download extremely quick. If you exit before downloading, the cached full file is deleted.

**Comment by damonlynch** [comment]
I need the log files. From your home directory run this command from the terminal:
```
tar cvf ~/rpd-log.tar -C ~ .cache/rapid-photo-downloader/log ".config/Rapid Photo Downloader/Rapid Photo Downloader.conf
```

Then create a new issue.

**Comment by eMPee584** [comment]
Thanks I have reported another issue, this should be only about a new option to disable thumbnail generation for rapid / privacy preserving operation.
