### ISSUE TITLE
Make program killable from the command line

### ISSUE THREAD

**Issue by eMPee584** [damonlynch/rapid-photo-downloader#233]
At the moment  keyboard interrupt when running from terminal does not abort the program:

```
KeyboardInterrupt
ERROR    Encountered problem when closing long-running ExifTool process
ERROR    Encountered problem when closing long-running ExifTool process
ERROR    Encountered problem when closing long-running ExifTool process
ERROR    Encountered problem when closing long-running ExifTool process
ERROR    Encountered problem when closing long-running ExifTool process
ERROR    Encountered problem when closing long-running ExifTool process
^C
```

I would suggest resetting the interrupt signal handler to the default action, `signal.signal(signal.SIGINT, signal.SIG_DFL)`, at least that makes it easily killable when run from the command line..

**Comment by damonlynch** [comment]
You are welcome to submit a patch. The program uses multiple kernel level processes, by design. See also https://github.com/damonlynch/rapid-photo-downloader/blob/main/raphodo/tools/utilities.py#L41

**Comment by eMPee584** [comment]
Well this is against the `/usr/bin/rapid-photo-downloader` I have on debian, couldn't find it in this repo:

```
--- rapid-photo-downloader.orig 2024-08-20 22:24:09.509987966 +0200
+++ rapid-photo-downloader  2024-08-20 22:24:20.018043694 +0200
@@ -2,6 +2,7 @@
 # EASY-INSTALL-ENTRY-SCRIPT: 'rapid-photo-downloader==0.9.36','gui_scripts','rapid-photo-downloader'
 import re
 import sys
+import signal
 
 # for compatibility with easy_install; see #2198
 __requires__ = 'rapid-photo-downloader==0.9.36'
@@ -29,5 +30,6 @@
 
 
 if __name__ == '__main__':
+    signal.signal(signal.SIGINT, signal.SIG_DFL)
     sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
     sys.exit(load_entry_point('rapid-photo-downloader==0.9.36', 'gui_scripts', 'rapid-photo-downloader')())
```

**Comment by damonlynch** [comment]
I did not write that script. I'm unsure if it is created by Debian or is the result of universal Python packaging procedures, i.e., setuptools.

That crucial point aside, did you test it to ensure that all child processes terminate? Also, does it terminate gracefully (giving it a chance to clean up), or is it equivalent to kill -9?

**Comment by eMPee584** [comment]
Yeah in the [debian repo](https://salsa.debian.org/debian/rapid-photo-downloader) I could also not find it, seems to be generated.

It's brutal, the process tree is eradicated the same instance 😀
.. maybe the better fix is to not hang on the splash screen 😄
