### ISSUE TITLE
Hanging on splashscreen on first run, maxing out CPU and RAM

### ISSUE THREAD

**Issue by eMPee584** [damonlynch/rapid-photo-downloader#234]
![rapid-memory-increase_2024-08-20_22-16-47](https://github.com/user-attachments/assets/9a98fa4f-c8b0-44bf-875c-e50e1fd1cd17)
[rpd-log.tar.gz](https://github.com/user-attachments/files/16681387/rpd-log.tar.gz)

**Comment by damonlynch** [comment]
What distro and distro version is this on?

**Comment by eMPee584** [comment]
debian unstable, package version `0.9.36-1.1`

**Comment by damonlynch** [comment]
Is there any chance you also use Jupyter? I ask because Jupyter also uses the Python binding to ZeroMQ. If there is a problem with how Rapid Photo Downloader uses ZeroMQ that Jupyter has solved, that could be useful information.

**Comment by damonlynch** [comment]
I did a brand-new install of Debian unstable in a virtual machine. I could not replicate the bug. One thing I noted was that the packages for the base system are newer than yours. Have you tried running a full upgrade?

**Comment by damonlynch** [comment]
I'm closing the issue because I cannot replicate it. If you can replicate it using the latest packages on Debian testing, please feel free to reopen the issue.
