### ISSUE TITLE
Error message: "sub-folder preferences should not end with a / " 

### ISSUE THREAD

**Issue by Brandipo** [damonlynch/rapid-photo-downloader#237]
every time i start the program, this message appears:

"Le preferenze del programma non sono valide

Le preferenze della sotto-cartella non dovrebbero terminare con un / "

(it's italian)

**Comment by damonlynch** [comment]
One or more of your custom preferences for subfolder generation contains a / at the end. You should remove this. Do you know how to do this?

**Comment by damonlynch** [comment]
Or possibly file naming. It is worth checking both. If you have difficulty, share the contents of this file:

`~/.config/Rapid Photo Downloader/Rapid Photo Downloader.conf`

**Comment by damonlynch** [comment]
Closing due to lack of response
