### ISSUE TITLE
RPD install on Gentoo again not working

### ISSUE THREAD

**Issue by AxelG-DE** [damonlynch/rapid-photo-downloader#240]
Hey there.

many times I could sneak around and got RPD running on Gentoo, but as of now (Dec 2024) I am again unable to install it neither thru virtualenv nor directly, eventho I have followed the instrutions using the pip-uninstall script.

Anyone here made it happen? If so, how?

**Comment by damonlynch** [comment]
Just a guess, but does the Gentoo package use the `install.py` script? I removed this script from Rapid Photo Downloader, as it had become an intolerable maintenance burden.

If I were you, I would install all of Rapid Photo Downloader's non-python dependencies (specified in README). Then, install Rapid Photo Downloader into an isolated virtual environment using `pipx` or  a similar technology (I have not been able to follow closely what `uv` is doing in this regard). That should work.

**Comment by AxelG-DE** [comment]
Hi Damon, there is no Gentoo package, hence I downloaded the latest install.py from your webpage. Maybe I should have read more thoroughly and not just "collecting" for informations. I will go to the readme and see, what I can do...

**Comment by AxelG-DE** [comment]
Oh no... I will not inject that many deps manually to my gentoo, that will mess up my system. Also INSTALL.md does not really say how to than install via pipx but says something about hatch wich is over my head :-( 

Looks there is no way for me and time to say good bye :''''''-( 
Loved RPD besides the hassle every now and then need ages to install it again.  It would be so easier as an C application and just "make"... SIGH

**Comment by damonlynch** [comment]
Hatch is a fantastic modern build system for Python applications. It is far superior to older standards like setuptools.

**Comment by AxelG-DE** [comment]
not part of gentoo's repo either

**Comment by AxelG-DE** [comment]
and `pip install hatch` does not work either

**Comment by AxelG-DE** [comment]
o.k. I made it to run pip install hatch in the virtual env  and then also ran the hatch command inside my cloned RPD dir, seems w/o errors. But subsequently I cannot find binaries and within the KDE menu, the entry does react but finally nothing popped up...

**Comment by damonlynch** [comment]
You need to manually install the .desktop file in the location KDE expects on your system.  [See this primer](https://wiki.archlinux.org/title/Desktop_entries).

**Comment by AxelG-DE** [comment]
I copied the file to ~/.local/share/applications, checked the chmod is set to 744 but yet it does not start

**Comment by damonlynch** [comment]
does it start from the command line?

**Comment by AxelG-DE** [comment]
Nope, I get the following error-codes (sorry they are all German but basically each lines complain about not found or not a valid pointer or such...
[RPD-error.txt](https://github.com/user-attachments/files/18160451/RPD-error.txt)

Yeah you said, "install missing deps manually". Which I skipped for several reasons:
- I was waiting for error messages during the compile phase and can then decide
- it is against the philosophy of Gentoo to install deps manually and hence there is a big risk to mess the system, which I try to avoid as much as possible

Today (17th Dec) I will have a scheduled electrical power out for repair, so I might be w/o my PC for half the day....

**Comment by AxelG-DE** [comment]
Thanks for your patience!

There is no Gentoo packaging for RPD at all, so there is nothing to fix. I am a user only and with too many sh!t on my shoes already so I am not able to be a maintainer for such a package and even not able to actually do it, even though experienced gentoo devs say it is easy to make an ebuild...

you say "_install Rapid Photo Downloader using pipx or uv_" but INSTALL.md says I should use hatch build...  That confuses me. (I even do not know how to invoke a re-build of anything  changes e.g. makes me git pull. Re-invoking hatch just shows me the tar file but I cannot see anything is going on)

There are other voices too, saying Gentoo is on its down slope for this and that reason. Me I wouldn't be able to argue with the gentoo devs. They have their own pride and self confidence but actually also competences (go and see on libera-chat #gentoo). I started with gentoo decades ago, when it was the mere DIY thing, understanding your own system and also about stability and being up to date. I am reluctant to just run away when hurdles come and learn a new admin-philosophy (e.g. ARCH) and I have seen quite some distros like debian, mandrake, redhat, SUSe and ubuntu, so I can say I don't really like any of 'em for individual reasons....
...sorry for drifting into philosophic...

**Comment by AxelG-DE** [comment]
### Dependencies situation on current gentoo

**Not in Repo** even I do not easily find an overlay containing it

1. python-gphoto2
2. show-in-filemanager
3. pyheif
4. Hatch --> overlay gpo.zugaino.org
5. Hatch-gettext
6. Hatch-argparse-manpage

**Unclear/unknown whether it is the correct one or not**

1. Python gobject introspection modules
there are:
[I] dev-libs/gobject-introspection
[I] dev-libs/gobject-introspection-common
[I] dev-python/pygobject
2. QT5 Plugin für reading TIFF images
3. QT5 plugin for rendering SVG

**The following are available just not installed on my personal system** (yet)

1. tornado
2. Colour
3. imobiledevice-tools
4. ifuse

**Comment by damonlynch** [comment]
The Qt5 related packages may already be part of the PyQt5 Gentoo installation. 

The other packages are all python packages that Hatch can handle. 

If I were you, to keep things simple, just use hatch directly to install Rapid Photo Downloader as I stated in the INSTALL.md. It should install the Python package dependencies. 

Do note that python gobject-introspection will almost certainly require header files for certain C libraries. I don't know what they are on Gentoo. That will be the most tricky part of the install. You should install these packages first before attempting to install Rapid Photo Downloader.


Probably I should not have earlier recommended uv or pipx, because they are more for people who use Python all the time.

**Comment by damonlynch** [comment]
You should start it from the command line.

**Comment by AxelG-DE** [comment]
installing wheel into the venv and modify the .desktop file did the trick

**Comment by negril** [comment]
A few notes from the other side. The `INSTALL.md` mentions `hatch build -t sdist`, but that doesn't result in a install.
If you then copy the desktop integration file into `${XDG_DATA_HOME}/applications`, you get the menu entry but the `Exec=` line in the desktop file expects the `rapid-photo-downloader` executable to be in `PATH`. Which is most likely the case.

This is what I ended up giving him to install.
```bash
#!/usr/bin/env bash

set -e

rm -Rf rapid-photo-downloader

git clone --depth=1 https://github.com/damonlynch/rapid-photo-downloader

cd rapid-photo-downloader

python -m venv .venv --system-site-packages --symlinks

source .venv/bin/activate

pip install --upgrade pip hatch

hatch build -t wheel

pip install dist/rapid_photo_downloader-*.whl

mkdir -p ~/.local/share/applications/
cp share/applications/net.damonlynch.rapid_photo_downloader.desktop ~/.local/share/applications/

sed -e "s#Exec=#Exec=$(dirname "$(realpath .venv/bin/rapid-photo-downloader)")/#g" \
  -i ~/.local/share/applications/net.damonlynch.rapid_photo_downloader.desktop
```

**Comment by AxelG-DE** [comment]
Dear @negril 

yet again thanks for your patience and support!


> Which is most likely the case.

Schould that line be --> _Which is most likely **not** the case?_
(hopefully this does not end up embarrising for me having limited English knowledge :smile: )

**Comment by negril** [comment]
Nah. You are correct.

**Comment by AxelG-DE** [comment]
With a little bit distance I understand Damon's comment "you should start it from the command line" better or different today :-/ With a bit more concise explanation of "it" that might have gone smoother :smile: 

- I remember, I did search for the executable and what I found, I also remember, I checked the file date and what I found appeared to me as it was the old attempt. Otherwise I would have been fine to just modify an old shell script of mine to start RPD
- On the contrary  I started the desktop file (silly, huh) and even reported my action here. If that would have been recognized, things might have gone smoother as well :smile:
- Maybe I should have told Damon more clearly that I am not a coder-dude but a simple user and need a different level of guidance (but isn't that clear from my responses?)

@damonlynch if you like and if @negril is fine with it, I would update the [article on pixls.us](https://discuss.pixls.us/t/howto-install-rpd-on-current-gentoo-may-2022-as-ebuild-is-still-missing-in-repo/30902)
