### ISSUE TITLE
Has someone installed it successfully on Windows?

### ISSUE THREAD

**Issue by javierguzman** [damonlynch/rapid-photo-downloader#25]
Hello all, 

I discovered Rapid Photo Downloader around two months ago and I really like it. However, for non-relevant issues, I have had to move back to Windows 10.

Rapid Photo Downloader does not seem to be prepared for Windows, even though it is written (apparently) in Python which should make it fairly portable though it has some stuff that is not ready for Windows like os.getuid function. I have been reading and playing around without any success. Considering that the biggest dependency was gphoto and in this repository I see it can be installed with pip, it should be pretty straight forward, shouldn't it?

Has someone tried successfully? Any hint?

Sorry, I know this is not a "code issue" but is the only place I found to ask.

Thank you in advance and kind regards,
Javier Guzman

**Comment by damonlynch** [comment]
Have you tried actually running libgphoto2 on Windows? Last time I checked it's not an officially supported configuration by its developers. There are several serious challenges. For example, how do you instruct Windows to release control of the USB camera connection and give it to libgphoto2? Without that, it is _impossible_ for libgphoto2 to access the camera.

If you want to take this further I strongly encourage you to prioritize getting libgphoto2 to work on Windows first.

**Comment by javierguzman** [comment]
Hello Damon!

Thank you for your quick response. I have tried before to make it run on Windows looking some Github repositories. However, I have stopped as soon as I have seen: 

"Given python-gphoto2 will almost certainly be installed from PyPi, the development packages for libgphoto2 and Python3 must be installed first, e.g. libgphoto2-dev and python3-dev"

When I have seen that in this repository I have imagined that the functionality of the library has been ported somehow to Python. From your words I guess this is not the case and you still need a fairly native Windows library.

Now I think about it, I do not normally connect my camera to transfer photos. I just take the SD card, copy and paste into a folder and then I use that folder as my source photo for importing.

By any chance there is no easy switch to turn off the camera connection feature so I do not care about libgphoto2 and use the rest of the functionality?

Thank you again.

**Comment by damonlynch** [comment]
Downloading from memory cards in a card reader is not a problem. It's relatively easy to port the program to do only that. The problem is that some people become angry when they learn the program cannot download from their camera or mobile phone. They then rate the program "one star" for failing to meet their expectations.

**Comment by javierguzman** [comment]
For those people I could argue that is better that minimal functionality than not having anything on Windows, but yes I understand the point and the impact of the rating. Could you give me a couple of bullet points of the steps I should follow to disable the libgphoto2? At least for myself; I cannot do any development right now because I am trying to launch my own application (not related to photography) at the moment but I would like in future to try this. In the meantime I guess I will do it manually as I was doing it in the past.

Thank you.

**Comment by damonlynch** [comment]
Sorry I don't have time to work on Rapid Photo Downloader these days. I suggest you use a specialized program written for Windows instead.

**Comment by javierguzman** [comment]
I do not understand, I was asking for a couple of hints about where to start so I can do it myself in future, not you. But I will figure it out on my own. I close this.
