### ISSUE TITLE
iPhone7 serial number format not recognized

### ISSUE THREAD

**Issue by sulphur-mercurius** [damonlynch/rapid-photo-downloader#30]
Hello, I’m on Linux Kubuntu 20.4 (LTS).
The required libraries fuse, ifuse and libimobiledevice-utils are installed.
Installed Rapid Photo Downloader 0.9.27a1 successfully (no error messages detected).
Connected my iPhone 7 / IOS 14.7.1 and ‘trusted’ it.
I always started Rapid Photo Downloader first and then plugged in the iPhone.
Connected it many times, alas, only this pop-up window appears and then … nothing else happens.
![Rapid-iPhone](https://user-images.githubusercontent.com/72442197/127733892-7c970f9d-6ffe-4599-ba49-f8119dac213b.png)
[rpd-bug-report-20210731.tar.gz](https://github.com/damonlynch/rapid-photo-downloader/files/6910897/rpd-bug-report-20210731.tar.gz)

**Comment by damonlynch** [comment]
The log file indicates the first point of major concern is that the serial number udev reports for your device is in a format that Rapid Photo Downloader currently does not know how to handle. In fact it is totally different from the format I've seen thus far for iPhones. 

With the phone plugged in and Rapid Photo Downloader not running, run the following commands and share the output here:

```bash
idevicepair list
idevicepair validate
idevicename
```

**Comment by sulphur-mercurius** [comment]
Here is the output of the required commands.

**Comment by damonlynch** [comment]
Thanks. What model is your phone?

**Comment by sulphur-mercurius** [comment]
iPhone 7 with IOS 14.7.1

**Comment by damonlynch** [comment]
Alpha 2, released just now, should work. Please let me know if it does not.
