### ISSUE TITLE
[feature] Allow use of none/empty job codes with renaming patterns

### ISSUE THREAD

**Issue by tekaeren** [damonlynch/rapid-photo-downloader#34]
When adding `job code` field to dir or filename pattern, the job code is required.
Sometimes I want to just download files, skipping the `job code` and not changing the rename/dir templates.

If no `job code` is selected, RPD could just treat it as empty and not add it as part of file path, or file/dir name.

**Comment by damonlynch** [comment]
Sorry, but I do not agree with this proposed workflow. The program would need to pop up an error message every time confirming the user does not want a Job Code for the download. It's quicker and easier for you to create a new renaming preset without the Job Code and use that instead.
