### ISSUE TITLE
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats on Python 3.10

### ISSUE THREAD

**Issue by damonlynch** [damonlynch/rapid-photo-downloader#37]
This problem occurs in the thumbnail extractors in Rapid Photo Downloader, causing them to crash. It is caused by a bug PyQt 5 when running on Python 3.10. PyQt 5.15.6 solves the problem. Either install PyQt5.15.6 yourself using pip, or simply run the `install.py` script to take care of it for you.

**Comment by e11o** [comment]
Does this require 0.9.28? I'm still getting this error with an up-to-date Arch install, which includes python 3.10 and PyQT 5.15.6.

```❯ pacman -Qi rapid-photo-downloader python-pyqt5
Name            : rapid-photo-downloader
Version         : 0.9.27-2
Description     : Photo and video downloader
Architecture    : any
URL             : https://www.damonlynch.net/rapid/
Licenses        : GPL3
Groups          : None
Provides        : None
Depends On      : desktop-file-utils  gstreamer  hicolor-icon-theme  libgexiv2  libnotify  python-arrow  perl-image-exiftool  python-colour  python-dateutil  python-easygui  python-gobject  python-gphoto2  python-psutil  python-pymediainfo  python-pyqt5  python-pyzmq
                  python-requests  python-setuptools  python-sortedcontainers  python-babel  python-tornado  python-pyxdg  qt5-imageformats  udisks2  python-tenacity  qt5-svg  python-show-in-file-manager
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 27.81 MiB
Packager        : Evangelos Foutras <foutrelis@archlinux.org>
Build Date      : Tue 14 Dec 2021 04:14:48 AM EST
Install Date    : Thu 06 Jan 2022 04:14:30 PM EST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

Name            : python-pyqt5
Version         : 5.15.6-6.1
Description     : A set of Python bindings for the Qt5 toolkit
Architecture    : x86_64
URL             : https://riverbankcomputing.com/software/pyqt/intro
Licenses        : GPL
Groups          : pyqt5
Provides        : qt5-python-bindings
Depends On      : python-pyqt5-sip  qt5-base
Optional Deps   : python-opengl: enable OpenGL 3D graphics in PyQt applications
                  python-dbus: for python-dbus mainloop support [installed]
                  qt5-multimedia: QtMultimedia, QtMultimediaWidgets [installed]
                  qt5-tools: QtHelp, QtDesigner
                  qt5-svg: QtSvg [installed]
                  qt5-webkit: QtWebKit, QtWebKitWidgets
                  qt5-xmlpatterns: QtXmlPatterns [installed]
                  qt5-declarative: QtQml, qmlplugin [installed]
                  qt5-serialport: QtSerialPort
                  qt5-websockets: QtWebSockets
                  qt5-connectivity: QtNfc, QtBluetooth
                  qt5-x11extras: QtX11Extras [installed]
                  qt5-remoteobjects: QtRemoteObjects
                  qt5-speech: QtTextToSpeech [installed]
                  qt5-quick3d: QtQuick3D
Required By     : bauh  calibre  manjaro-printer  python-pyqt5-webengine  qutebrowser  rapid-photo-downloader  torbrowser-launcher
Optional For    : hplip  python-pillow
Conflicts With  : pyqt5-common
Replaces        : None
Installed Size  : 27.04 MiB
Packager        : Bernhard Landauer <oberon@manjaro.org>
Build Date      : Tue 21 Dec 2021 06:19:52 AM EST
Install Date    : Mon 03 Jan 2022 07:50:26 AM EST
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

**Comment by damonlynch** [comment]
It's a problem in PyQt5 when run with Python 3.10. I don't know why it is not working as expected with PyQt5.15.6. It was fixed by the PyQt developer.

**Comment by unsermanninchina** [comment]
@e11o Exactly the same problem on Manjaro. Last log and config attached.
[rapid-photo-downloader.log](https://github.com/damonlynch/rapid-photo-downloader/files/8014991/rapid-photo-downloader.log)
[Rapid Photo Downloader.conf.txt](https://github.com/damonlynch/rapid-photo-downloader/files/8014996/Rapid.Photo.Downloader.conf.txt)
Same versions here.

**Comment by damonlynch** [comment]
@unsermanninchina the log file you attached contains no mention of PY_SSIZE_T_CLEAN. Reproduce the error, generate the tar file using the program, gzip the tar file, and then attach it here.

In any case, given the problem is in the PyQt5 package on your system, if you install PyQt from PyPi it might solve it. Try it:

`python3 -m pip install --user PyQt5`

You will need python3-pip installed, or whatever it is called on Manjaro.

If that fixes the problem, then that shows that the Manjaro package of PyQt5 has a problem.

**Comment by unsermanninchina** [comment]
Thank you both!I didn't find a special place to file a bug for trhe maintainer, so I filed it at the Manjaro forum: 
[Package faulty - rapid-foto-downloader not working with pyqt5](https://forum.manjaro.org/t/package-faulty-rapid-foto-downloader-not-working-with-pyqt5/102071)

**Comment by unsermanninchina** [comment]
Thanks again, @damonlynch !
I created an issue at [Manjaro's Gitlab page](https://gitlab.manjaro.org/packages/extra/python-pyqt5/-/issues/2)
