### ISSUE TITLE
Possibility to disable destination storage check

### ISSUE THREAD

**Issue by cankarm** [damonlynch/rapid-photo-downloader#40]
In old versions of the application it was possible to use it even inside the containerized environment. Currently there is an issue as application cannot determine the size of disks correctly and therefore the download is not allowed. 

Please see the screenshot and squares with numbers (1,2,3). The "Download" is grayed out and detected sizes of storage are 17 MB. The correct sizes of disks storages are in GB and TB and there is more then enough space for the content. 

Is there a possibility to create an option in settings or some other trick that would not check (or not take it into account) the size of the destination? The application was the best for years, but it is now useless for my use case.

![rapidDownloader png ‎- Photos](https://user-images.githubusercontent.com/2518386/143311683-e1546dd5-b06d-469e-830c-26ed4bf8bbc4.png)

**Comment by damonlynch** [comment]
First, what container are you using? Second, why can the container not report storage information correctly? In other words, why does the file system not correctly report its size and space used? Have you configured it incorrectly, or is the a bona fide rationale for this clearly wrong value?

**Comment by cankarm** [comment]
Thanks for a fast response. It's a QNAP's NAS "linux station" -> https://www.qnap.com/solution/linux-station-app/en/

Actually I don't have much things to configure and it is pre-prepared so it already works with the NAS HDMIs, network, VNC... that's why I'm quite limited with the configuration part. I'm not sure why it is presented wrong.

**Comment by damonlynch** [comment]
Have you tried asking in the QNAP forum? The storage values should not be wrong like that! Something is not configured correctly. 17 MB for both the camera and the destination volume makes no sense at all. Please do what you can with the QNAP experts to resolve it. Otherwise the changes needed to the Rapid Photo Downloader code are not trivial, and would not be implemented until next year (I already have a long list of things to do on the project).

**Comment by cankarm** [comment]
@damonlynch thanks for paying attention on this issue, 

I guess that I find a solution. Let me test it first and then I will describe how this workaround goes. I would like first it first, to see if 2000+ photos will be successfully transferred, before I wrote something that it might not work.

**Comment by damonlynch** [comment]
Did it work?

**Comment by cankarm** [comment]
Sorry for not responding. Yes, it seems it works using some symbolic links. After Christmas I can write how exactly I have done this and also highlight potential issues.

Thanks @damonlynch to keep an eye on this.

**Comment by damonlynch** [comment]
Ok, thanks @cankarm.
