### ISSUE TITLE
Unity7 Desktop Environment unknown

### ISSUE THREAD

**Issue by Dohle** [damonlynch/rapid-photo-downloader#46]
Tried the latest install.py today (vs 0.9.27).

user@lorentz:~/Software/rapidphotodownloader$ python3 install.py
Restarting script using system python...

Restarting script using /usr/bin/python3

setuptools 45.2.0 is up to date
wheel 0.34.2 is up to date
Downloading https://launchpad.net/rapid/pyqt/0.9.27/+download/rapid-photo-downloader-0.9.27.tar.gz (8.43 MB)
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:00

Determining most appropriate PyQt5 package...
...will use PyQt5 packaged by Ubuntu 20.04.3 LTS.

Querying package system to see if an older version of Rapid Photo Downloader is installed (this may take a while)...
Checking if previous version installed with pip...
Found existing installation: rapid-photo-downloader 0.9.26
Uninstalling rapid-photo-downloader-0.9.26:
  Successfully uninstalled rapid-photo-downloader-0.9.26

Installing application requirements...

Looking in indexes: https://pypi.python.org/simple/
Ignoring importlib-metadata: markers 'python_version < "3.8"' don't match your environment
Requirement already satisfied: psutil>=3.4.2 in /usr/lib/python3/dist-packages (from -r /tmp/tmp884jww2u (line 4)) (5.5.1)
Requirement already satisfied: gphoto2>=1.8.0 in /usr/lib/python3/dist-packages (from -r /tmp/tmp884jww2u (line 5)) (1.9.0)
Requirement already satisfied: pyzmq>=16.0.2 in /usr/lib/python3/dist-packages (from -r /tmp/tmp884jww2u (line 6)) (18.1.1)
Requirement already satisfied: pyxdg>=0.25 in /usr/lib/python3/dist-packages (from -r /tmp/tmp884jww2u (line 7)) (0.26)
Requirement already satisfied: arrow>=0.9.0 in /usr/lib/python3/dist-packages (from -r /tmp/tmp884jww2u (line 8)) (0.15.5)
Requirement already satisfied: python-dateutil>=2.7 in /usr/lib/python3/dist-packages (from -r /tmp/tmp884jww2u (line 9)) (2.7.3)
Requirement already satisfied: PyPrind>=2.9.4 in /home/hk/.local/lib/python3.8/site-packages (from -r /tmp/tmp884jww2u (line 10)) (2.11.3)
Requirement already satisfied: colorlog>=2.6 in /usr/lib/python3/dist-packages (from -r /tmp/tmp884jww2u (line 11)) (4.1.0)
Requirement already satisfied: easygui>=0.98.1 in /usr/lib/python3/dist-packages (from -r /tmp/tmp884jww2u (line 12)) (0.98.1)
Requirement already satisfied: colour in /usr/lib/python3/dist-packages (from -r /tmp/tmp884jww2u (line 13)) (0.1.5)
Requirement already satisfied: pymediainfo>=2.2.0 in /usr/lib/python3/dist-packages (from -r /tmp/tmp884jww2u (line 14)) (4.1)
Requirement already satisfied: sortedcontainers in /usr/lib/python3/dist-packages (from -r /tmp/tmp884jww2u (line 15)) (2.1.0)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r /tmp/tmp884jww2u (line 16)) (2.22.0)
Requirement already satisfied: tornado in /usr/lib/python3/dist-packages (from -r /tmp/tmp884jww2u (line 17)) (5.1.1)
Requirement already satisfied: tenacity in /usr/lib/python3/dist-packages (from -r /tmp/tmp884jww2u (line 18)) (6.0.0)
Requirement already satisfied: pillow>=5.1.0 in /usr/local/lib/python3.8/dist-packages (from -r /tmp/tmp884jww2u (line 19)) (8.4.0)
Requirement already satisfied: Babel in /usr/lib/python3/dist-packages (from -r /tmp/tmp884jww2u (line 21)) (2.6.0)
Collecting show-in-file-manager>=1.1.1
  Downloading show_in_file_manager-1.1.1-py3-none-any.whl (28 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.8/dist-packages (from show-in-file-manager>=1.1.1->-r /tmp/tmp884jww2u (line 22)) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.8/dist-packages (from packaging->show-in-file-manager>=1.1.1->-r /tmp/tmp884jww2u (line 22)) (3.0.6)
Installing collected packages: show-in-file-manager
Successfully installed show-in-file-manager-1.1.1

Installing Python support for HEIF / HEIC...
Requirement already satisfied: pyheif in /home/user/.local/lib/python3.8/site-packages (0.6.0)
Collecting pyheif
  Downloading pyheif-0.6.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.8 MB)
Requirement already satisfied: cffi>=1.0.0 in /home/user/.local/lib/python3.8/site-packages (from pyheif) (1.15.0)
Requirement already satisfied: pycparser in /home/user/.local/lib/python3.8/site-packages (from cffi>=1.0.0->pyheif) (2.21)
Installing collected packages: pyheif
  Attempting uninstall: pyheif
    Found existing installation: pyheif 0.6.0
    Uninstalling pyheif-0.6.0:
      Successfully uninstalled pyheif-0.6.0
Successfully installed pyheif-0.6.1

Installing application...

Processing /tmp/tmpr6iwqd22/rapid-photo-downloader-0.9.27.tar.gz
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: rapid-photo-downloader
  Building wheel for rapid-photo-downloader (setup.py): started
  Building wheel for rapid-photo-downloader (setup.py): finished with status 'done'
  Created wheel for rapid-photo-downloader: filename=rapid_photo_downloader-0.9.27-py3-none-any.whl size=6555650 sha256=db3c84f9961e4095fc551a4e1433577ba058d9737e47e7862a021369bddfd054
  Stored in directory: /home/user/.cache/pip/wheels/63/05/05/4d320bf4b2e1a537fd1d5f9c869d380e6fc70856bc71120d8a
Successfully built rapid-photo-downloader
Installing collected packages: rapid-photo-downloader
Successfully installed rapid-photo-downloader-0.9.27
Using existing path /home/hk/.local/bin for program executable

Installing man pages into /usr/local/share/man/man1
If you uninstall the application, remove these manpages yourself.
sudo may prompt you for the sudo password.

sudo /bin/cp /home/user/.local/share/man/man1/rapid-photo-downloader.1 /usr/local/share/man/man1/rapid-photo-downloader.1
[sudo] password for hk: 
sudo /bin/cp /home/user/.local/share/man/man1/analyze-pv-structure.1 /usr/local/share/man/man1/analyze-pv-structure.1
Done.
user@lorentz:~/Software/rapidphotodownloader$ rapid-photo-downloader 
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/showinfm/system/linux.py", line 784, in linux_desktop
    return LinuxDesktop[env]
  File "/usr/lib/python3.8/enum.py", line 387, in __getitem__
    return cls._member_map_[name]
KeyError: 'unity:unity7:ubuntu'

...

  File "/home/user/.local/lib/python3.8/site-packages/showinfm/system/linux.py", line 786, in linux_desktop
    raise Exception("The desktop environment {} is unknown".format(env))
Exception: The desktop environment unity:unity7:ubuntu is unknown

It ran with vs 0.9.26

**Comment by damonlynch** [comment]
Fixed in 0.9.28

**Comment by Dohle** [comment]
Added the returned alternative in "/home/user/.local/lib/python3.8/site-packages/showinfm/system/linux.py", near line 786:

...
    if env == "unity:unity7":
        env = "unity"
    elif env == "unity:unity7:ubuntu":
        env = "unity"
    elif env == "x-cinnamon":
        env = "cinnamon"
...

It runs now.

**Comment by Dohle** [comment]
You are too quick :-)
