### ISSUE TITLE
setuptools >= 60.0 failing due to "assert '_distutils' in core.__file__, core.__file__" error

### ISSUE THREAD

**Issue by fiepfiep** [damonlynch/rapid-photo-downloader#61]
I created and activated a virutal environment.
Then I run the install script.

```
 philippe  (e) rapid-photo-downloader  ~  rapid-photo-downloader  python install.py --virtual-env                       1   main 
Using virtual environment for installation using pip.
Detected Linux distribution Fedora Linux 35 (Workstation Edition) 
Traceback (most recent call last):
  File "/home/philippe/rapid-photo-downloader/install.py", line 14637, in <module>
    main()
  File "/home/philippe/rapid-photo-downloader/install.py", line 4148, in main
    packages, local_pip = pip_packages_required(distro_details.distro)
  File "/home/philippe/rapid-photo-downloader/install.py", line 665, in pip_packages_required
    import setuptools
  File "/home/philippe/rapid-photo-downloader/venv/lib64/python3.10/site-packages/setuptools/__init__.py", line 8, in <module>
    import _distutils_hack.override  # noqa: F401
  File "/home/philippe/rapid-photo-downloader/venv/lib64/python3.10/site-packages/_distutils_hack/override.py", line 1, in <module>
    __import__('_distutils_hack').do_override()
  File "/home/philippe/rapid-photo-downloader/venv/lib64/python3.10/site-packages/_distutils_hack/__init__.py", line 71, in do_override
    ensure_local_distutils()
  File "/home/philippe/rapid-photo-downloader/venv/lib64/python3.10/site-packages/_distutils_hack/__init__.py", line 59, in ensure_local_distutils
    assert '_distutils' in core.__file__, core.__file__
AssertionError: /usr/lib64/python3.10/distutils/core.py
```

Honestly, I would prefer to get rid of distutils and use setuptools instead.

the rpm package in fedora repo is also broken and does not even launch.

**Comment by damonlynch** [comment]
The `install.py` script does not import `distutils`. I do believe you're seeing a bug in `setuptools`. It would be extremely helpful if you could determine the most recent version of `setuptools` that is not broken. Try the recent releases until you determine the most recent one that works. Then I will adjust the setup script accordingly. I would be **truly grateful** if you can do this.

The [update package request for Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=2031866) has been languishing for some time. If you know someone in Fedora who can look into it that would also be helpful.

**Comment by fiepfiep** [comment]
Thanks.
I will investigate.
Probably indeed a setuptools issue, but adding a pyproject.toml might
help...

Philippe

Op zo 6 feb. 2022 15:31 schreef Damon Lynch ***@***.***>:

**Comment by damonlynch** [comment]
If recent setuptools now require a pyproject.toml then please let me know about that too. Perhaps the backwards compatibility of setuptools is not ideal? I haven't looked into it.

**Comment by fiepfiep** [comment]
problem is: even in a virutalenv, setuptools still uses my system's setuptools version.
pyproject.toml seems to be the future, we might want do adopt.
[link to pep518](https://www.python.org/dev/peps/pep-0518/)
There you can specify your build setup requirements, such as setuptools, wheel and pip.
For me, removing this seems to solve the issue:

```
    try:
        import setuptools
    except ImportError:
        packages.append(pip_package("setuptools", local_pip, distro))
```

**Comment by fiepfiep** [comment]
system setuptools version:
setuptools             57.4.0 (July 2021)

If I revert my venv setuptools version to 57.4, the installer works fine!!
however, in order to do this I had to use --do-not-upgrade-pip" argument when running the installer.
Otherwise, 'update_pip_setuptools_wheel' will decide to update it. probably because of function `is_recent_pypi_package`.
using version.

**version 59.7 also works.
version 60+ does not.**

**Comment by damonlynch** [comment]
Thanks, that's very helpful. Either `setuptools` is deliberately making a backwards incompatible change (which is somewhat annoying), or else, it has a bug. Probably the former.

My other project uses pyproject.toml, which was easy because it is a much simpler project: https://github.com/damonlynch/showinfilemanager

However, bringing the setup.py in Rapid Photo Downloader up-to-date with pyproject.toml is not trivial. Python packaging can be difficult.

**Comment by damonlynch** [comment]
There was in fact a change that breaks things in [setuptools v60.0.0](https://setuptools.pypa.io/en/latest/history.html#breaking-changes).
