### ISSUE TITLE
feature request: wayland hidpi

### ISSUE THREAD

**Issue by fiepfiep** [damonlynch/rapid-photo-downloader#62]
using fedora GNOME on Wayland, scale set to 200%.

GUI appears to be blurry.

`Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.`

**Comment by damonlynch** [comment]
Do just as it says on command line: set the environment variable as instructed. [Source](https://wiki.archlinux.org/title/wayland#Qt).

**Comment by fiepfiep** [comment]
thanks this worked for me!
