### ISSUE TITLE
Warning dialog fails to appear when iOS device utility applications are missing, causing crash

### ISSUE THREAD

**Issue by speddle** [damonlynch/rapid-photo-downloader#64]
[rapid-photo-downloader.log](https://github.com/damonlynch/rapid-photo-downloader/files/8052116/rapid-photo-downloader.log)
[Rapid Photo Downloader.conf.log](https://github.com/damonlynch/rapid-photo-downloader/files/8052118/Rapid.Photo.Downloader.conf.log)
So the crash handler generated a tar file which git hub does not accept so I included the log and conf contained (and renamed the conf to conf.log so I could upload it here) 

HISTORY
Went to back up Iphone Xs IOS 15.1 after about 6 months to elementary OS 5.1.7 Hera using RapidPhoto 09.26.
After a LONG time (more than 1/2 hour) it was stuck on 99% so I killed it.
Then I restarted and allowed an auto-update to 09.28.
Tried to restart app and got crashhandler.
killed any rapid processes I could find and still crashed..
Tried unplugging iphone and now it starts BUT crashes when I
1- replug iphone
2- disable devices
3- re-enable devices (BOOM)

I will try and go back to the previous version.

Steve

OK just found the python errors and not sure if they got in the log file but could be VERY useful:
Traceback (most recent call last):
  File "/home/mo/.local/lib/python3.6/site-packages/raphodo/rapid.py", line 2973, in devicesViewToggledOn
    self.searchForCameras()
  File "/home/mo/.local/lib/python3.6/site-packages/raphodo/rapid.py", line 5521, in searchForCameras
    device.set_download_from_camera(model, port)
  File "/home/mo/.local/lib/python3.6/site-packages/raphodo/devices.py", line 281, in set_download_from_camera
    name = idevice_get_name(self.idevice_udid)
  File "/home/mo/.local/lib/python3.6/site-packages/raphodo/storageidevice.py", line 163, in idevice_get_name
    camera_error_code=CameraErrorCode.devicename,
  File "/home/mo/.local/lib/python3.6/site-packages/raphodo/storageidevice.py", line 132, in idevice_run_command
    check=True,
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1278, in _execute_child
    executable = os.fsencode(executable)
  File "/usr/lib/python3.6/os.py", line 800, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by damonlynch** [comment]
I forgot to add, the best approach for now is to run the install.py script from here: https://damonlynch.net/rapid/download.html
That should install the missing software to access the iPhone.

**Comment by damonlynch** [comment]
Finally, I do **not** recommend using any version of Rapid Photo Downloader earlier than 0.9.27 to download from an iPhone. Prior to 0.9.27 gPhoto2 was used to download from the iPhone, which is not reliable. 0.9.27 and new use [a very different way](https://libimobiledevice.org/) to access the iPhone

**Comment by speddle** [comment]
You mentioned missing files. You may not have noticed as it is in the title but I went with the auto update from 0.9.26 to 0.9.28 as I haven't used it for a while and likely missed the 0.9.27. Is it possible the missing files were supposed to be included in the 26 to 27 update? That could explain why they aren't there.
I downloaded the latest installer and installed from the command line
And here are the log files.
[rpd-bug-report-20220211.zip](https://github.com/damonlynch/rapid-photo-downloader/files/8052782/rpd-bug-report-20220211.zip)
.

**Comment by damonlynch** [comment]
The problem with the missing files is not because you didn't upgrade to 0.9.27. Instead, the problem was that when I released  0.9.28, I neglected to set a flag that meant the upgrade could only proceed by downloading the install.py script. The install.py script is necessary to install new packages using the system package installer, e.g. apt, dnf, etc. The built-in upgrader cannot install the system packages.

If you have run the install.py script and installed 0.9.28, you should have the software needed to reliably access the iPhone.

However, it seems possible that there is still the potential problem of exiv2 crashing, which is a serious problem. If you see thumbnailing is never finishing, then this is likely why. Although I suppose it is possible that libmediainfo could be crashing when trying to read a video file, but I have not seen them before.  

As a workaround for a potential exiv2 crash, you could try setting the photo metadata to be read with ExifTool: https://damonlynch.net/rapid/documentation/#miscellaneousnpreferences
If his does not solve the problem, then unset that preference, as exiv2 is much faster than ExifTool.

**Comment by speddle** [comment]
I really like ifuse ...
Here is what I found:
exiv2 is already the newest version (0.25-3.1ubuntu0.18.04.11).
Read and Write support for HEIC is fully compliant in 7.3.0. Exiv2 0.27.4 support now Base Media Format (HEIC, AVIF) to read write metadata.
The iphone has has HEIC files:
Exiv2 exception in print action for file 121APPLE/IMG_1241.HEIC:
121APPLE/IMG_1241.HEIC: The file contains data of an unknown image type

**Comment by damonlynch** [comment]
Thanks. Yes ifuse is much better than using gPhoto2. The root problem is that Apple does not strictly follow the PTP standard that gPhoto2 relies on. iPhone file access is just as bad on Windows with its PTP implementation. 

Are you able to share the crashing image with me, strictly in private? If not I understand. Some images are too private.

**Comment by speddle** [comment]
I think the problem is i am running Elementary which is always based on a older UBUNTU LTS, and I haven't updated to the latest Elementary yet. And ubuntu0.18.04.11 doesn't have a new enough version of exiv2 to support the NEW Apple standard HEIC. I use elementary because I find Pantheon to be the best "desktop" for my weak eyes. But is does tend to fall behind on software versions :-(
I have many HEIC files to choose from. I assume there is a way to send personal messages on Github, or I could email you one.

**Comment by damonlynch** [comment]
That's a great point. The version of exiv2 you have now is in fact too old for newer generation files. So there is no need to investigate any further crashes with it. My mistake for forgetting that earlier today.

If you don't want to upgrade to the latest Elementary then the good news is you can update ExifTool anytime. Just download the latest version and put its location on the PATH. I assume you know what I mean by this?

**Comment by speddle** [comment]
OK so I know what I need to do to get it working.
For now I can use ifuse to make sure I have the files.
Thanks again.

**Comment by damonlynch** [comment]
On further thought, installing the latest exiftool is as simple as placing it in ~/.local/bin
Rapid Photo Downloader automatically uses ifuse behind the scenes so you don't need to mess about with it every time yourself.

**Comment by speddle** [comment]
OK so I have version 10.8 and created a link to it in my ~/.local/bin dir.
But now I am trying to connect to the iphone Xs using rapidphoto and it is hard to get it to connect. whereas mounting and unmounting using ifuse and fusemount -u is rock solid.
rapid-photo-downloader 
QApplication: invalid style override 'adwaita' passed, ignoring it.
	Available styles: Windows, Fusion
ERROR    Cannot set download destination display:  does not exist
ERROR    Cannot set download destination display:  does not exist
ERROR    Unable to access camera Apple iPhone: GP_ERROR. Is it locked?

But I know it is unlocked as I just did a fusemount -u after looking at the dirs?
Note I am on a computer still running 26, as I wanted to verify the flakeyness wasn't just on one computer. I was able to make it find the phone a couple of times but mostly just this error. Maybe I should update this computer as well ...

**Comment by damonlynch** [comment]
Don't mount the phone yourself using ifuse. Don't open it in the file manager. 

Just leave it unmounted. Plug it in with or without Rapid Photo Downloader running. Run Rapid Photo Downloader if it is not running.

Sometimes you need to remove the phone and plug it in again if it does not connect in a prompt manner.

**Comment by damonlynch** [comment]
I'm just saying that with the old version of the software you have, sometimes when you plug in the phone ifuse and the other "i" utility programs might take a while to respond. Whether you do it yourself by hand or use Rapid Photo Downloader is irrelevant to that. You could face it if you use them yourself, or get Rapid Photo Downloader to do it. No difference. If that happens, simply unplug and plug again. That's all.

**Comment by speddle** [comment]
Got it working on the 28 version computer now by pre-mounting using ifuse and pointing your program at the mounted dir.
I also added the exiftool link to .local/bin. 
This seems more pain free for me. Not sure why, but my success rate on re-plugging is way too low.
