### ISSUE TITLE
[0.9.29] Issues with dark theme

### ISSUE THREAD

**Issue by algent-al** [damonlynch/rapid-photo-downloader#66]
There are some issues with dark theme with new version or RPD 0.9.29

Before with 0.9.28
![2 9 28](https://user-images.githubusercontent.com/46356616/155856206-7db7b888-b540-4493-b691-5bd1ede12d09.png)

New version 0.9.29
![0 9 29](https://user-images.githubusercontent.com/46356616/155856211-6d72a8b3-c28a-4022-94a9-7bd2256a9808.png)

Tried different GTK themes, and issue is still the same.
Themes I tried:
- pocillo-gtk-theme
- qogir-gtk-theme
- plata-theme

OS: Solus Budgie

**Comment by damonlynch** [comment]
That looks terrible. What year was your distro released? I tested it on Fedora 35 (Gnome) and KDE Neon (cutting edge KDE) and it looked fine.

**Comment by algent-al** [comment]
> That looks terrible. What year was your distro released? I tested it on Fedora 35 (Gnome) and KDE Neon (cutting edge KDE) and it looked fine.


Solus is a rolling release distro and everything is up to date for `rapid-photo-downloader`.
Not sure what changed in last version that can affect the dark GTK themes.

**Comment by algent-al** [comment]
I maintain `RPD` for Solus, and I am holding back for now this release until this issue is resolved. Version 0.9.28 is fine for now.

**Comment by damonlynch** [comment]
What versions of PyQt5 and Qt5 does it currently use?

**Comment by algent-al** [comment]
Qt5 -  [5.15.3](https://dev.getsol.us/source/qt5-base/browse/master/package.yml)
PyQt5 - [5.15.4](https://dev.getsol.us/source/python3-qt5/browse/master/package.yml)

**Comment by damonlynch** [comment]
PyQt 5.15.6 contains a critical bug fix required for Python 3.10.

Regardless of the version of Python 3 found in Solus, to test to see if the out of date PyQt5 is making a difference to this problem, install PyQt 5.15.6 from PyPi for your user only:

`python3 -m pip install -U --user PyQt5`

And see what effect that has on the dark theme.

**Comment by damonlynch** [comment]
Another thing I can see from the screenshots is that in 0.9.29 the Qt 5 Fusion theme is being used. 0.9.29 enforces the use of Fusion because with some distro themes parts the program's appearance can look pretty awful. Nonetheless you can run it with the command line option `--force-system-theme` , as is discussed in the changelog.

**Comment by damonlynch** [comment]
Below is a fresh install of Solus Budgie with Rapid Photo Downloader from git, and all other packages from the Solus repositories. The git version of Rapid Photo Downloader is almost identical to 0.9.29 — the only difference is simple refactoring to move some Python modules into Python packages. Everything looks fine:

![Solus Rapid Photo Downloader](https://user-images.githubusercontent.com/1749868/155886641-0f209326-5693-4cc1-92c1-1a1d78eaebe4.png)

When you test Rapid Photo Downloader, are you testing it in your personal setup, or in a clean environment?

**Comment by algent-al** [comment]
No change with PyQt5 from pip.
Using `--force-system-theme` I get a nice looking RPD like in your test.

> When you test Rapid Photo Downloader, are you testing it in your personal setup, or in a clean environment?
I test it in my main machine, without any special configuration. 

Did a test on a Solus Budgie and Solus MATE installed in Virtual Box.
For Solus Budgie `--force-system-theme` doesn't work. RPD is always with light theme.
In Solus MATE RPD starts in dark theme and no issues.

**Comment by damonlynch** [comment]
Did you try a fresh install of Solus Budgie, with a clean /home and default system setup?

**Comment by algent-al** [comment]
> Did you try a fresh install of Solus Budgie, with a clean /home and default system setup?

Solus Budgie in VB was almost clean, but I will try again.

**Comment by algent-al** [comment]
No, issues on a fresh install.

**Comment by damonlynch** [comment]
Do you mean you are seeing issues in a fresh install, or you are not? If you are, can you include a screenshot. Thanks.

**Comment by algent-al** [comment]
RPD on Solus Budgie (Virtual Box), fully updated.

![RPD-fresh](https://user-images.githubusercontent.com/46356616/155890462-5674cb2e-45c3-407e-8212-f131febd0276.png)

**Comment by damonlynch** [comment]
That is how it is supposed to look.

**Comment by algent-al** [comment]
Is it possible to make `--force-system-theme` default and have it as option in RPD preferences?

**Comment by damonlynch** [comment]
No, because some distro themes make the application look terrible. A few months ago some GTK app developers got together and declared their frustration at the fact that a bunch of GTK themes would make their apps look broken. The same problem exists with with Qt apps. It is a real problem. If you use a non-Fusion theme in Rapid Photo Downloader and make the window look small so the main UI scroll bars appear on the left and the right, you'll see what I mean.

**Comment by damonlynch** [comment]
I do believe this issue can now be closed. Please reopen if something new can be added.
