### ISSUE TITLE
[Feaute Request] Export without Subfolder creation

### ISSUE THREAD

**Issue by ruffson** [damonlynch/rapid-photo-downloader#7]
`version: 0.9.18`

I love the program, but I have just one feature request.

My library is basically only one folder currently and when I export photos to it, I would like to do that without managing subfolders.

I did not find a way of getting around the subfolder setting. I tried leaving it empty or just putting in a slash, but that did not work.

Thank you for your work!

**Comment by damonlynch** [comment]
Rapid Photo Downloader does not *export* photos. So I assume you are talking about the process of *importing* photos into some kind of folder structure.  

If you want to download/import photos into a single folder, it's really easy. For example, suppose you want to import into `/home/ruffson/Pictures`, specify the download folder as `/home/ruffson/`, and the subfolder as `Pictures`, using the text entry feature. You can enter in whatever subfolder name you want.
