### ISSUE TITLE
Installation via install.py - something went wrong determining the status of existing packages.

### ISSUE THREAD

**Issue by paydart** [damonlynch/rapid-photo-downloader#72]
Installation via "python3 install.py" fails with the following output on my laptop:

```
Detected Linux distribution openSUSE Leap 15.3 
Sorry, something went wrong determining the status of existing packages.
Please try running this script again later.
```
Unfortunately, it doesn't share more details. I have tried several times but always get the same failure. My OS is up-to-date. 

I've also tried to install it into a Python virtual environment and it worked fine. I can live with this but I would like to find out why the standard installation doesn't work.

**Comment by damonlynch** [comment]
Thanks for your bug report. I assume you are a different person to the person here? https://discuss.pixls.us/t/v0-3-20-fails-to-install-on-tumbleweed/30121

**Comment by paydart** [comment]
Hello. Yes, I am a different person. It seems we both use OpenSUSE - he uses Tumbleweed (rolling version), I use Leap (regular release version).

**Comment by damonlynch** [comment]
What is your system locale (language) set to?

**Comment by damonlynch** [comment]
Sorry I've been totally unable to work on this. For an explanation, [see why](https://discuss.pixls.us/t/help-needed-from-folks-who-know-python-to-support-users-due-to-medical-problem/30138).

**Comment by paydart** [comment]
No problem at all, I can live with the installation in the virtual python environment. Get well soon! ;)

**Comment by damonlynch** [comment]
I'm closing this bug because the installation script is now depreciated.
