### ISSUE TITLE
WSL2

### ISSUE THREAD

**Issue by Riverman778** [damonlynch/rapid-photo-downloader#74]
Windows subsystem for linux preview (win 11)

I couldn't copy log files from linux so i did copy n paste to text files

sudo apt-get install -y rapid-photo-downloader
[Rapid Photo Downloader.txt](https://github.com/damonlynch/rapid-photo-downloader/files/8627358/Rapid.Photo.Downloader.txt)
[rapid-photo-downloader.log](https://github.com/damonlynch/rapid-photo-downloader/files/8627359/rapid-photo-downloader.log)

**Comment by damonlynch** [comment]
[You need to upgrade to a supported version](https://damonlynch.net/rapid/documentation/#wsl)

**Comment by Riverman778** [comment]
Where might I find the latest version? I have been running the latest version rpd successfully on virtualbox windows host ubuntu vm using installation script on another computer (win10). New computer win11  tried same configuration ubuntu 22.04 problems installing any applications. Ubuntu 20.04 most applications ok except rpd installed from script. Freezes complete session.   Not sure how to install from command line in wsl2

**Comment by Riverman778** [comment]
I did install on wsl2 ubuntu using wget  https://raw.githubusercontent.com/damonlynch/rapid-photo-downloader/main/install.py
(regular file download from github wraps in html) 

Lots of error messages when loading  but it does appear to be working. Have not tried importing photos yet.

**Comment by damonlynch** [comment]
I'm glad to hear. In future it's always best to use an official release for the `install.py` script: https://damonlynch.net/rapid/download.html

**Comment by damonlynch** [comment]
If you find the program useful, please consider making a donation. I worked for one month full-time to get it working under WSL. I discuss some of the extensive work I had to do [here](https://www.reddit.com/r/bashonubuntuonwindows/comments/r4yjgc/my_experience_porting_a_linux_program_to_wslg_wsl/). The documentation for using Rapid Photo Downloader under WSL is [here](https://damonlynch.net/rapid/documentation/#wsl).

**Comment by Riverman778** [comment]
Hola Damon

fyi I believe I did donate when I first started using your program several
years ago.

A
