### ISSUE TITLE
Provide tags in the repo aligned to the releases

### ISSUE THREAD

**Issue by thomas-mc-work** [damonlynch/rapid-photo-downloader#84]
In other source code repos it's an approved convention to add a tag in the code repository for each release. That makes it easier for other developers to show differences e.g. when looking for regressions.

**Comment by damonlynch** [comment]
This is indeed a task that can be done. As you might be aware, the project was for many years hosted solely on Launchpad. Releases are still made there. However, I agree it would be good to have release tags here.

**Comment by damonlynch** [comment]
Done for 0.9.34
