### ISSUE TITLE
Sequence Numbers for each day

### ISSUE THREAD

**Issue by hahihohehe** [damonlynch/rapid-photo-downloader#90]
I have a small feature request:

I store my images on the file system in a folder for each session.
RPD supports the folder generation perfectly with job codes.
The image numbering from my camera really annoys me and I change the numbering to YYMMDD_#### so that for each day the counter starts at 0 and goes up for each image at that day.
This numbering is the shortest I can find, with the date in the name.
Unfortunately, RPD does currently not support this (or I could not find it) and I work around this limitation by downloading the images for each day separately and resetting the sequence number after each download.

Is it possible to support this numbering?

**Comment by damonlynch** [comment]
See https://damonlynch.net/rapid/documentation/#sequencenumbers
