### ISSUE TITLE
Fedora 37 error: gstreamer1-libav unavailable

### ISSUE THREAD

**Issue by riley-brandt** [damonlynch/rapid-photo-downloader#92]
Hello,

After upgrading from Fedora 35 to 37, Rapid Photo Download stopped launching. The error message is:

```
Traceback (most recent call last):
  File "/home/username/.local/bin/rapid-photo-downloader", line 5, in <module>
    from raphodo.rapid import main
ModuleNotFoundError: No module named 'raphodo'
```

When trying to install with the install.py file, I got the following error:

`The following package is unavailable on your system: gstreamer1-libav`

Thankfully, I was able to install version 0.9.33 from the Fedora repository.

**Comment by damonlynch** [comment]
Thanks for your bug report. Please see this message: https://discuss.pixls.us/t/rapid-photo-downloader-0-9-34-is-released/33356

If at all possible, please submit a pull request with the fix made to install.py.

**Comment by riley-brandt** [comment]
Sorry to hear about the hand! :(

I ended up with soft tissue damage along my thumb joint from too much mouse use during game dev. A year and half later, and it's still an issue.

I'm just a javascript guy right now. If I dive into python, I'll try to patch it.

**Comment by Nicryc** [comment]
I don't use _rapid-photo-downloader_ but note that the package `gstreamer1-libav` doesn't exist anymore neither in the Fedora repos nor the RPM Fusion repos. It has been replaced by the `gstreamer1-plugin-libav` package in the Fedora repos. Hope it helps.
