### ISSUE TITLE
Error when downloading photos in Fedora 37 Gnome 43

### ISSUE THREAD

**Issue by SolidCapo** [damonlynch/rapid-photo-downloader#93]
Created my own rename convention and couldn't download photos. (<Fecha de la imagen (AAAA-MM-DD)> <Fecha de la imagen (HH)>.<Fecha de la imagen (MM (minutos))>.<Fecha de la imagen (SS)>)

Once the error appeared for all the photos, couldn't select them to try and download them again.

**No se puede copiar el archivo [_DSC3139.ARW](file:///402)
Error: 5 Error de entrada/salida**

This appeared when i reescanned the usb drive.
`Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/raphodo/rapid.py", line 5264, in proximityGroupsGenerated
    if self.temporalProximity.setGroups(proximity_groups=proximity_groups):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/raphodo/proximity.py", line 2388, in setGroups
    self.temporalProximityModel.updatePreviouslyDownloaded(
  File "/usr/lib/python3.11/site-packages/raphodo/proximity.py", line 1351, in updatePreviouslyDownloaded
    row = self.groups.uid_to_row(uid=uid)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/raphodo/proximity.py", line 1191, in uid_to_row
    return self.uids.uid_to_col2_row(uid=uid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/raphodo/proximity.py", line 713, in uid_to_col2_row
    return self._col2_row_index[uid]
           ~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: b'\xa7\x03-\xe3eXG}\xb8\xd1\xb7b\x05\xcb\xab!'`

[rpd-bug-report-20221220-1.tar.gz](https://github.com/damonlynch/rapid-photo-downloader/files/10271374/rpd-bug-report-20221220-1.tar.gz)

**Comment by damonlynch** [comment]
That's probably a long-standing bug with respect to the Timeline. It's a very difficult to determine the root cause of the problem, because it involves user interaction with different Timeline permutations that are difficult to reproduce.
If you can reproduce the problem so that you know how to precisely trigger the bug in the Timeline, that would be **extremely** helpful for me. But you may find it difficult to reproduce, in which case, you can proceed with the download is normal.

**Comment by SolidCapo** [comment]
Don't know what happened, but i've connected the usb again, and now it worked fine. Thank you.

**Comment by damonlynch** [comment]
It doesn't surprise me. It's an obscure bug that rarely occurs. I have not been able to reliably reproduce it.
