### ISSUE TITLE
Build finished with status 'error'

### ISSUE THREAD

**Issue by Sagebati** [damonlynch/rapid-photo-downloader#95]
Hi,

I'm on Arch, I think I installed all the necessary requirements, but I get this message. I didn't find a way to print more meaningful error messages. I tried the installation on a venv. 

![image](https://user-images.githubusercontent.com/10544280/210138071-7f92c9b9-cc3c-46bb-9243-dde1f51f85ed.png)

![log.txt](https://github.com/damonlynch/rapid-photo-downloader/files/10327398/log.txt)

**Comment by damonlynch** [comment]
On Arch, you should install it like this: `sudo pacman -S rapid-photo-downloader`
Do not use the install.py script, it is not supported.

**Comment by Sagebati** [comment]
My usecase was to contribute not to install it globally. Maybe I missed a contribute guide how to have a write-run-debug work flow didn't see any main

**Comment by damonlynch** [comment]
You are correct&mdash;I have not written a guide on how to contribute to the project.

Installing into a virtual environment is easy if you have experience with Python. Install the required non-Python packages from Arch, which you can find in the Arch rapid-photo-downloader package. Then install the Python packages into the python virtual environment. Look in the requirements.txt file for the required python packages.
