### ISSUE TITLE
RPD silently dropping the first 2 character of camera model name on directory name

### ISSUE THREAD

**Issue by gordhub** [damonlynch/rapid-photo-downloader#96]
Hi,

I'm a happy long-time user of RPD. However, I recently reinstalled RPD 0.9.34 on my system after a clean install of Ubuntu 22.04.1 LTS. I include the camera model name in my directory names. Since the reinstall, the camera name is showing up as T20 instead of X-T20 in directory names. I do use fairly long directory names, as I try to make the job codes useful, but nowhere near the 256 char maximum.

Confirmation that the camera is idenfitied as X-T20 in the metadata:
```
someguy@somesys:~/Pictures/2023-01-02_rouge-national-urban-park-monarch-trail_T20$ exiftool 20230102-163347-0099-DSCF0810.raf | grep T20
Camera Model Name               : X-T20
Software                        : Digital Camera X-T20 Ver2.10
```
Feel free to get in touch if you need any additional info.

Thanks!

[rapid-photo-downloader.log](https://github.com/damonlynch/rapid-photo-downloader/files/10336934/rapid-photo-downloader.log)

**Comment by damonlynch** [comment]
Please take a look at the documentation here: https://damonlynch.net/rapid/documentation/#renamemetadata
And confirm that you are using exactly the same renaming scheme that you use before. It's possible you are now using a slightly different scheme, i.e. one of the different model name options differs.

**Comment by gordhub** [comment]
Thanks Damon, that was it. I had inadvertently switched from "Camera Model (original case)" to "Short Camera Model (original case)". Sorry for the noise.

**Comment by damonlynch** [comment]
No worries. Glad it is sorted.
